### PR TITLE
add features from nbrownus 

### PR DESCRIPTION
**Pull request by deathowl**

### CODE REVIEW

**Comment by jdoss** [comment]
Think we can get this merged?

**Comment by deathowl** [comment]
@jdoss yeah, i'm doing it right now

**Comment by deathowl** [comment]
@jdoss i was working on this during the weekend, but tests for @nbrownus's master are breaking

**Comment by nbrownus** [comment]
I've cleaned up the failing test on my fork if you'd like to consider including the changes again.

Our use case is tightly coupled to the data format change for timers and meters. #20 does something very similar to mine but in a better way for you to maintain backwards compatibility.

**Comment by JohnMaguire** [comment]
@deathowl Hate to bug you but any updates on this one?

**Comment by deathowl** [comment]
Yes, i'll do it tonight

**Comment by deathowl** [comment]
Merged #20 , so resolving this. @JohnMaguire  sorry for taking this long

**Pull request closed without merging**
